
name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync to HF Hub
        uses: huggingface/hub-action@v1
        with:
          repo-token: ${{ secrets.UGGING_FACE_TOKEN    }}
          repo-id: martn37/proyecto_agro

          




