
name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # uses: huggingface/actions/hub-action@v1 # Usar la acci贸n oficial y versi贸n v1

      - name: Sync to HF Hub
        #   uses: huggingface/hub-action@v1
        # uses: huggingface/hub@v1
        # uses: huggingface/hub-action@main
        uses: huggingface/actions/hub-action@v1 # Usar la acci贸n oficial y versi贸n v1
        
        with:
          # repo-token: ${{ secrets.UGGING_FACE_TOKEN    }}
          repo-token: ${{ secrets.HF_TOKEN }}
          repo-id: martn37/proyecto_agro

          




